name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Inject Supabase Secrets
        run: |
          sed -i "s|SEARCH_REPLACE_SUPABASE_URL|${{ secrets.SUPABASE_URL }}|g" login.html signup.html
          sed -i "s|SEARCH_REPLACE_SUPABASE_KEY|${{ secrets.SUPABASE_KEY }}|g" login.html signup.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Deploys the current folder
          branch: gh-pages # This creates a clean branch for your live site
